server:
  port: 8072
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance: 
    preferIpAddress: true 

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseSeviceId: true
  
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      gateway:  
        access: unrestricted
